Add features for the backend in the full-stack capstone project: Tesla Car Test Drive Reservation
hafiz1379/Tesla-car-booking-back-end pull request #20
Opened 2023-12-12 03:41 UTC by ivangonzalez224

## Final PR - API app for Full Stack Capstone project - Tesla Car Test Drive Booking

Link to the front end app Pull Request: https://github.com/ivangonzalez224/Tesla-car-booking-front-end/pull/35

**Description:**

This pull request implements the following features for the Tesla car test drive booking API app:

**Database and schema:**
- Created the users, cars, and reservations tables.
- Added the seed data for cars and users.

**Routing:**
- Created the routes to sign in and sign out.
- Created the routes to create and delete a car.
- Created the routes to list and create a reservation.

**Authentication:**
- Added the the active_model_serializers and devise-jwt gems for user authentication from frontend to backend.
- Created the SessionsController for user authentication.
- Added User model with Devise authentication and JWT.
- Only admin users can access "Add car" and "Delete car" functionalities.

**Models and Controllers:**
- Created the user, car and reservation models including validations.
- Create the user, car and reservation API controllers including actions.
- 
**API Documentation:**
- Includes rswag-ui and gems.
- Added Rswag API and Rswag UI configuration.

**Technical Setup:**

Gitflow workflow implemented.
Postgres database used.

2023-12-12 09:57 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!









#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-12 09:57 UTC, Meltrust commented on spec/models/user_spec.rb
- [ ] In order for this spec file to work, you need to include the   `gem 'shoulda-matchers', '~> 3.1'` in your gemfile.  Kindly include it so your tests work.  Otherwise, rspec throws an error. 👍 

![image](https://github.com/hafiz1379/Tesla-car-booking-back-end/assets/57421823/fd0b15fa-024a-44d3-a1c9-7489f869a5a3)

2023-12-12 09:57 UTC, Meltrust commented on spec/models/reservation_spec.rb
> +end
- [ ] This file has no implemented examples.  Kindly remove it if not using it. 👍

2023-12-12 09:57 UTC, Meltrust commented on README.md
> +### Prerequisites
- [ ] Kindly, include in your readme file a "tests" section with specific instructions about how to run your tests. 👍

2023-12-12 09:57 UTC, Meltrust commented on README.md
> +## 📑 Database ERD <a name="erd"></a>
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2023-12-12 09:57 UTC, Meltrust commented on README.md
> +<img src='app/assets/images/table-tesla-car-booking.png' />
- [ ] Kindly, include in your instructions the required db commands that your users will need to run your backend app: ``rails db:create, rails db:migrate, rails db:seed``. 👍

2023-12-12 09:57 UTC, Meltrust commented on app/controllers/api/v1/cars_controller.rb
> +  end
- [ ] What happens here if the car is not successfully destroyed?  Kindly, add some error handling just like you did in the update method (line 25). 👍

2023-12-12 09:57 UTC, Meltrust commented on app/controllers/api/v1/reservations_controller.rb
> +  end
- [ ] What happens here if the reservation is not successfully destroyed?  Kindly, add some error handling just like you did in the update method (line 29). 👍

2023-12-12 21:30 UTC, ivangonzalez224 commented
Hi @Meltrust thank you for the review:
Changes done: 
- updated the destroy method in the cars and reservations controllers.
- included the gem shoulda-matchers.
- removed the test folder from the project.
- updated the readme file by adding the instructions to run the database and the tests.

2023-12-12 22:29 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight


- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2023-12-13 12:20 UTC, hafiz1379 commented
@Meltrust 
Thank you for investing time in reviewing our project and providing valuable feedback!

2023-12-13 12:20 UTC, merged